### ISSUE TITLE
Smart Charging

### ISSUE THREAD

**Issue by ccoltx** [valiquette/homebridge-easee#10]
I generate power using my Solar Panels and would like to charge my vehicle with the excess power. The easee wallbox supports this, see: https://developer.easee.cloud/docs/api-smart-charging#generation

The following API can be used to dynamically control the power level
https://developer.easee.cloud/reference/post_api-sites-siteid-circuits-circuitid-dynamiccurrent

**Comment by valiquette** [comment]
interesting, How would you detect your excess solar power? 
The issue I have is I don't have access to one of this chargers, i wrote this for someone based on another charger and it has been collecting dust for a while. If you are interested in helping test this then I may be able to help.  I have done something like this where a  thermostat accessory in HomeKit controls the amperage. 
-John

**Comment by ccoltx** [comment]
Ah, thank you for clarifying. I have no experience either, but I thought I would ask. I'm experimenting with different solutions, trying to find one which works. I will close this issue for now, let's see if I ever get too it.
