### ISSUE TITLE
Feature request: Expose Easee equalizer to HomeKit

### ISSUE THREAD

**Issue by kempd** [valiquette/homebridge-easee#14]
Hi,

I love this Homebridge plugin and I would like to make a feature request.

I like to expose the Easee equalizer to homekit, maybe also as a lightbulb as it also works with percentages.

It would be possible to increase or decrease the max output of the charger based on the current sun (If an inverter is exposed in homekit) and the current amount of total power currently being used in your household.

This would give control over the capacity fee that's being introduced in some countries while still maintaining the option to charge at a higher kW rate when the sun is shining.

Best regards.

**Comment by kempd** [comment]
![PNG-afbeelding - Copy](https://user-images.githubusercontent.com/49713226/211005681-191177e9-45de-41d2-bfac-cdebd3b3d408.png)

**Comment by valiquette** [comment]
I do not have access to these products. I originally wrote this plugin as a request with some testing support that I no longer have available. There are other enhancements I would have added if I had the ability to test them, including control for the amperage output (thermostat), and a sensor (humidity) for the amount of charge supplied which allowed for HomeKit automation.  Your ask seems pretty simple but I don't have any way to test it. If you want to help in this regard let me know.

**Comment by kempd** [comment]
I'm certainly willing to help, I can provide access to the equalizer.

**Comment by valiquette** [comment]
ok, I would need your access token/refresh token, this would give me some time to work on it before it expires. You could attach the debug logs with your account login credentials removed. I will delete the attachment once I have it

**Comment by kempd** [comment]
Is there a way I can reach out outside github (e-mail?)? (If you are open to that.)

**Comment by valiquette** [comment]
yes you can e-mail @ jvaliquette163@gmail.com

**Comment by valiquette** [comment]
Closing with publish of version 1.2.x
