### ISSUE TITLE
Plugin Freezes?

### ISSUE THREAD

**Issue by solbadguy2010** [valiquette/homebridge-easee#4]
Hi,
i now had it two times, that the plugin doesn't refelct changes i make in the original app.
I needed to restart homebridge to get it working again. There was no error in the log.

Any idea?

**Comment by valiquette** [comment]
There maybe a hint to why in the debug logging if you want to try and look at that. It may be that the connection used for the live updates gets closed and is not reconnecting on its own. I can try and reproduce this by dropping the network. I assume this is installed on a system that never sleeps?

**Comment by solbadguy2010** [comment]
Yes. This is a Raspi connected by LAN. Let me know how i can help.

**Comment by valiquette** [comment]
I was able to replicate and resolve this. You can test this yourself by dropping your network connection and watching the logs.

**Comment by solbadguy2010** [comment]
Tested. And you where right. I restarted the router prior to the connection losses due to updates. Now its working also after it was offline. Thank you!
