### ISSUE TITLE
Possible to not use Battery charge feature?

### ISSUE THREAD

**Issue by solbadguy2010** [valiquette/homebridge-easee#5]
Hi.
in my Eve app, i almost always see a warning about low battery from the car.
Since i do not use this feature, is it possible to not use it? Simply deleting my Car Info did not help.

**Comment by valiquette** [comment]
This must be something Eve does on its own as I am not setting the low battery state. Currently it is always there but I can suppress that if there is no car defined. This is a good ask, thanks

**Comment by solbadguy2010** [comment]
Yes, Eve reports this on its own.
Thank you for helping.

**Comment by valiquette** [comment]
battery service will now be automatically suppressed if no car is defined v1.1.6

**Comment by solbadguy2010** [comment]
Working great! Thank you?
