### ISSUE TITLE
Street error

### ISSUE THREAD

**Issue by JanVildk** [valiquette/homebridge-easee#8]
Gettings a "Failed to get info for build TypeError: Cannot read properties of null (reading 'street')" error.

**Comment by valiquette** [comment]
Do you have an address defined in your Easee app? Double check that first. The plugin is getting a response back that would appear to not have one.

**Comment by JanVildk** [comment]
I had under contact information and wasnt able to find other places to put it until now.. Just looked again and deep in the settings i found it.. Thanks it works now :)
