### ISSUE TITLE
Cannot read properties of null (reading 'street')

### ISSUE THREAD

**Issue by vbartels** [valiquette/homebridge-easee#9]
Hi,
I just installed the plugin but it didnt seem to work. 
I dialed in my account and it states:
`[28/07/2022, 10:39:05] [Easee Wallbox] Found account for NAME SURNAME`
Where my name is written correctly. So its seems to authenticate correctly.

Later in the log I see this:
```
[28/07/2022, 10:39:05] [Easee Wallbox] Failed to get info for build TypeError: Cannot read properties of null (reading 'street')
    at /usr/lib/node_modules/homebridge-easee/easeeplatform.js:84:66
    at Array.filter (<anonymous>)
    at /usr/lib/node_modules/homebridge-easee/easeeplatform.js:83:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Since I only have one chargeberry, I've not put a street in the configuration. The Wallbox is definetely online ans accessible.
Setting a street does not change the behavior.

**Comment by valiquette** [comment]
It is expecting a street on the Easee account side. You could try adding one to your charger's account.
The plugin can be blank or it can have a matching address

**Comment by vbartels** [comment]
Thanks! Adding a street in the easee app made it work.
